prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/Freshly/spicerack/master/spicerack-styleguide/rubocop.yml"
      path: ".rubocop.yml"

plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-54

exclude_patterns:
  - "**/bin/"
  - "**.gemspec"
  - "**/test_classes/"
  - "spec/spec_helper.rb"

ratings:
  paths:
    - "**.rb"
